Updated GitHub CI

diff --git a/.github/workflows/examples.yml b/.github/workflows/examples.yml
--- a/.github/workflows/examples.yml
+++ b/.github/workflows/examples.yml
@@ -33,7 +33,7 @@ jobs:
       with:
         xcode-version: latest-stable
     
-    - name: MTCExample - Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
-      run: xcodebuild -project "Examples/SwiftUI macOS/MTCExample/MTCExample.xcodeproj" -resolvePackageDependencies | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
-    - name: MTCExample - Build
-      run: xcodebuild build -project "Examples/SwiftUI macOS/MTCExample/MTCExample.xcodeproj" -scheme "MTCExample" -destination "generic/platform=macOS" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
+    - name: MTC Example - Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
+      run: xcodebuild -project "Examples/SwiftUI macOS/MTC Example/MTC Example.xcodeproj" -resolvePackageDependencies | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
+    - name: MTC Example - Build
+      run: xcodebuild build -project "Examples/SwiftUI macOS/MTC Example/MTC Example.xcodeproj" -scheme "MTC Example" -destination "generic/platform=macOS" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
